### ISSUE TITLE
`kubernetes_cluster_role` rule has incorrect validation

### ISSUE THREAD

**Issue by wjam** [terraform-providers/terraform-provider-kubernetes#285]
Currently, the attributes in the `kubernetes_cluster_role` rule element validates that the `api_groups` attribute is present but this doesn't match up with the validation performed by Kubernetes.

Using the example at the bottom of this issue as the starting ground, the rules appear to be:
* either apiGroups or nonResourceUrls must be present
* verbs must be present
* if the rule has apiGroups, then resource must be present
* if the rule has nonResourceUrls, then resource must not be present
* resourceNames can only be present with apiGroups but are optional

```
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: example
rules:
- apiGroups: [""]
  resources:
  - pods
  verbs: ["get"]
- nonResourceURLs: ["/metrics"]
  verbs: ["get"]
```
