### ISSUE TITLE
Provider should intake a "kubeconfig" output (instead requiring a file path)

### ISSUE THREAD

**Issue by sinneduy** [terraform-providers/terraform-provider-kubernetes#315]
cc @juleea

The getting started docs for EKS in terraform generates a [local](https://www.terraform.io/docs/configuration/locals.html) value in terraform that they expect to be output [into a file](https://learn.hashicorp.com/terraform/aws/eks-intro#configuring-kubectl-for-eks)

We should be able to take that local variable and input it into the kubernetes provider, and bypass the requirement for a file:

```
locals {
  kubeconfig = <<KUBECONFIG


apiVersion: v1
clusters:
- cluster:
    server: ${aws_eks_cluster.demo.endpoint}
    certificate-authority-data: ${aws_eks_cluster.demo.certificate_authority.0.data}
  name: kubernetes
contexts:
- context:
    cluster: kubernetes
    user: aws
  name: aws
current-context: aws
kind: Config
preferences: {}
users:
- name: aws
  user:
    exec:
      apiVersion: client.authentication.k8s.io/v1alpha1
      command: aws-iam-authenticator
      args:
        - "token"
        - "-i"
        - "${var.cluster-name}"
KUBECONFIG
}

output "kubeconfig" {
  value = "${local.kubeconfig}"
}

provider "kubernetes" {
  kubeconfig = "${local.kubeconfig}"
}

# Do stuff with the kubernetes provider here
```

However, the [options currently available](https://github.com/terraform-providers/terraform-provider-kubernetes/blob/master/kubernetes/provider.go#L20) to the kubernetes provider doesn't appear to support this.  The closest thing appears to be the [config_path](https://github.com/terraform-providers/terraform-provider-kubernetes/blob/master/kubernetes/provider.go#L64), but this requires us writing an [actual file to disk](https://github.com/terraform-providers/terraform-provider-kubernetes/blob/master/kubernetes/provider.go#L192) (that would presumably be checked into version control).

It could be something like this:

```
resource "local_file" "kubeconfig" {
    content     = "${local.kubeconfig}"
    filename = "${path.module}/kubeconfig"
}

provider "kubernetes" {
  kubeconfig = "${path.module}/kubeconfig"
}
```

But this seems kind of unpleasant.

Would love to get the devs thoughts on this, to see if the local file workaround is what you expect, or if you have other plans for the future.

**Comment by diclophis** [comment]
I am also getting stuck on this

**Comment by selslack** [comment]
It is a nice feature to have.

**Comment by darrylb-github** [comment]
This would help greatly when trying to create and bootstrap a cluster entirely from terraform using tools like atlantis. 

I can create a local file which will allow the first run to pass and create k8s resources, but any subsequent run without that file will not be able to plan as it can't auth with k8s to check the status of k8s resources until after the file is created. 

I can use static credentials to auth with k8s, but not when assuming a role via aws-iam-authenticator. E.g.

```
users:
- name: devel-03-user
  user:
    exec:
      apiVersion: client.authentication.k8s.io/v1alpha1
      command: aws-iam-authenticator
      args:
        - "token"
        - "-i"
        - "kubernetes-useast1-devel-03"
       - "-r"
       - "atlantis-role"
```

If the provider accepted raw input without relying on a file, I could avoid this dependency loop by passing in the kubeconfig value from a template and it means plans would pass without relying on a TF created file.
