### ISSUE TITLE
kubernetes_storage_class needs mountoptions support to be usable with azurefile

### ISSUE THREAD

**Issue by ljckennedy** [terraform-providers/terraform-provider-kubernetes#510]
To use azurefiles accross multiple pods you need to be able to configure the mountoptions.  This is not supported (or at least not documented). right now.

### Terraform Version
v0.12.0

### Affected Resource(s)
kubernetes_storage_class

Below seems to be the limit of supported configuration options:

### Terraform Configuration Files
```hcl
resource "kubernetes_storage_class" "azurefile" {
  metadata {
    name = "azurefile"
  }
  storage_provisioner = "kubernetes.io/azure-file"
  reclaim_policy      = "Retain"
  parameters = {
    skuName = "Standard_LRS"
  }
}
```
The below configuration is what is needed:

kubernetes yaml:
```
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: azurefile
provisioner: kubernetes.io/azure-file
mountOptions:
  - dir_mode=0777
  - file_mode=0777
  - uid=1000
  - gid=1000
parameters:
  skuName: Standard_LRS

```

### Expected Behavior
should support mountoptions

### Actual Behavior
Does not support mountoptions.

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform apply`

### Important Factoids
see https://docs.microsoft.com/en-us/azure/aks/azure-files-dynamic-pv
