### ISSUE TITLE
metrics support for kubernetes_horizontal_pod_autoscaler

### ISSUE THREAD

**Issue by marcosrmendezthd** [terraform-providers/terraform-provider-kubernetes#555]
Can we add external `metrics` support for the horizontal pod autoscaler resource?

### Terraform Version
Terraform v0.11.14

### Affected Resource(s)
- kubernetes_horizontal_pod_autoscaler

If this issue appears to affect multiple resources, it may be an issue with Terraform's core, so please mention this.

### Important Factoids
```
apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
...
spec:
  metrics:
  - external:
      metricName: pubsub.googleapis.com|subscription|num_undelivered_messages
      metricSelector:
        matchLabels:
          resource.labels.subscription_id: echo-read
      targetAverageValue: "2"
    type: External
...
```

### References
- https://cloud.google.com/kubernetes-engine/docs/tutorials/external-metrics-autoscaling
- https://kubernetes.io/docs/tasks/run-application/horizontal-pod-autoscale-walkthrough/
