### ISSUE TITLE
Clarify Network Policy documentation

### ISSUE THREAD

**Issue by stepanstipl** [terraform-providers/terraform-provider-kubernetes#600]
### Terraform Version
master / 0.12.7

```
Terraform v0.12.7
+ provider.kubernetes v1.9.0
```

### Affected Resource(s)
- kubernetes_network_policy

Documentation for `kubernetes_network_policy` rules seems incorrect.

Documentation for `ingress` (and `egress`) arguments says:
> ingress - (Optional) ... **If this field is empty then this NetworkPolicy does not allow any traffic** (and serves solely to ensure that the pods it selects are isolated by default).

If the argument is specified empty - `ingress {}`, this will result in `NetworkPolicy` with following spec being created:
```
spec:
  ingress:
    - {}
...
```
This policy **allows all traffic** (which is opposite to what the documentation says).

To achieve a policy that does not allow any traffic, the `ingress` argument has to be completely omitted.

I would suggest changing documentation to smth like:
_... If this field is empty then this NetworkPolicy allows all traffic. If this field is omitted then this NetworkPolicy does not allow any traffic (and serves solely to ensure that the pods it selects are isolated by default)._

Same applies to the `egress` argument.

---
Below are full examples of the above-described behavior:

Following manifest:
```hcl
resource "kubernetes_network_policy" "deny-default" {
  metadata {
    name      = "deny-default"
    namespace = "default"
  }

  spec {
    pod_selector {}

    ingress {}

    policy_types = ["Ingress"]
  }
}
```
will result in following `NetworkPolicy being created:
```yaml
apiVersion: extensions/v1beta1
kind: NetworkPolicy
metadata:
  name: deny-default
  namespace: default
spec:
  ingress:
  - {}
  podSelector: {}
  policyTypes:
  - Ingress
```
This policy **allows all traffic**.

To achieve a policy that does not allow any traffic, following manifest:
```hcl
resource "kubernetes_network_policy" "deny-default" {
  metadata {
    name      = "deny-default"
    namespace = "default"
  }

  spec {
    pod_selector {}

    policy_types = ["Ingress"]
  }
}
```
will result in following `NetworkPolicy being created:
```yaml
apiVersion: extensions/v1beta1
kind: NetworkPolicy
metadata:
  name: deny-default
  namespace: default
spec:
  podSelector: {}
  policyTypes:
  - Ingress
```
This policy **denies all ingress traffic**.
