### ISSUE TITLE
Post getting credentials: exec: exit status 2

### ISSUE THREAD

**Issue by sebolabs** [terraform-providers/terraform-provider-kubernetes#816]
**Terraform version**: `0.12.24`
**Kubernetes provider version**: `1.11.1`

**Error**
```
Post https://XXXXXXXXXXXXXX.yl4.eu-west-1.eks.amazonaws.com/api/v1/namespaces/kube-system/configmaps: getting credentials: exec: exit status 2
```
The above error message indicates that the cluster information can be successfully retrieved from the provided kube config file (see below).

**Config**
```
resource "local_file" "kube_config" {
  content    = module.eks_cluster.kube_config
  filename   = "/tmp/kubeconfig_${module.eks_cluster.cluster.id}"
}

provider "kubernetes" {
  config_path = local_file.kube_config.filename
}

resource "kubernetes_config_map" "aws_auth" {
  metadata {
    name      = "aws-auth"
    namespace = "kube-system"
  }

  data = {
    mapRoles = data.template_file.k8s_aws_auth_configmap_maproles.rendered
    mapUsers = data.template_file.k8s_aws_auth_configmap_mapusers.rendered
  }
}
```

**Kube config**
```
apiVersion: v1
clusters:
- cluster:
    server: https://XXXXXXXXXXXXXX.yl4.eu-west-1.eks.amazonaws.com
    certificate-authority-data: LS0tLS1CRUdJTi[...]UNBVEUtLS0tLQo=
  name: kubernetes
contexts:
- context:
    cluster: kubernetes
    user: aws
  name: aws
current-context: aws
kind: Config
preferences: {}
users:
- name: aws
  user:
    exec:
      apiVersion: client.authentication.k8s.io/v1alpha1
      command: aws
      args:
      - eks
      - get-token
      - --cluster-name
      - my-cluster
      - --role
      - arn:aws:iam::XXXXXXXXXXXXXX:role/ekscluster-provisioner
      - --region
      - eu-west-1
```

The user that runs Terraform is an admin and can assume the role specified in the kube config.

What am I missing?
