### ISSUE TITLE
Updating a deployment spec.selector should not force recreate

### ISSUE THREAD

**Issue by fonsecas72** [terraform-providers/terraform-provider-kubernetes#833]
### Community Note
* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version and Provider Version
v0.12.18
v1.11.1

### Affected Resource(s)
- deployment

### Terraform Configuration Files
any simple deployment

### Expected Behavior
When applying a change to the spec.selector it should not force the recreation of the deployment but just apply it instead, just like a "kubectl apply" works

### Actual Behavior
it forces the recreation

### Steps to Reproduce
1. `terraform apply`
2. `add a label to spec.selector.match_labels `
3. `add a label to spec.template.metadata.labels `
4. `terraform apply`

**Comment by fonsecas72** [comment]
```
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: nginx-test
spec:
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - image: nginx:1.17.10
        name: nginx
      restartPolicy: Always
```
`kubectl apply -f <<above>>`

all good ✅ 

adding 1 label to matchLabels and to metadata.labels 

`kubectl apply -f <<above with 1 more label>>`

all good. ✅  k8s leaves a pod behind 🤷‍♂️ , but I'm 🆗  with that. No downtime ✅  

When using terraform, it will replace the deployment and I will have downtime ❌  
Deployments should never be replaced how i see it
