### ISSUE TITLE
SecurityContextConstraints

### ISSUE THREAD

**Issue by NeQuissimus** [terraform-providers/terraform-provider-kubernetes#873]
### Description

I am trying to wrap [kube2iam](https://github.com/jtblin/kube2iam) and as part of that I have run into `SecurityContextConstraints`. (see below YAML)
There does not seem to be a way for me to encode this in Terraform.
Is this potentially a missing `kind` in this provider?

```yaml
kind: SecurityContextConstraints
apiVersion: v1
metadata:
  name: kube2iam
allowPrivilegedContainer: true
allowHostPorts: true
allowHostNetwork: true
runAsUser:
  type: RunAsAny
seLinuxContext:
  type: MustRunAs
users:
- system:serviceacount:kube-system:kube2iam
``` 

### Potential Terraform Configuration

```hcl
resource "kubernetes_security_context_constraints" "kube2iam_constraints" {
  api_version = "v1"
  metadata {
    name = "kube2iam"
  }
  allow_privileged_container = true
  allow_host_ports = true
  run_as_user = "RunAsAny"
  se_linux_context = "MustRunAs"
  users = ["system:serviceacount:kube-system:kube2iam"]
}
```

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment
